//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hopita_Ibn_Sina_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Ordonnance_Medicament = new HashSet<Ordonnance_Medicament>();
            this.Rendez_vous = new HashSet<Rendez_vous>();
            this.Test = new HashSet<Test>();
        }
    
        public int Id_Doc { get; set; }
        public string Nom_Doc { get; set; }
        public string Prenom_Doc { get; set; }
        public System.DateTime DateNaissance_Doc { get; set; }
        public string Doc_specialite { get; set; }
        public int Doc_experience { get; set; }
        public string Doc_phone { get; set; }
        public string Doc_addr { get; set; }
        public string Doc_pass { get; set; }
        public byte[] Doc_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordonnance_Medicament> Ordonnance_Medicament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendez_vous> Rendez_vous { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Test { get; set; }
    }
}
