//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hopita_Ibn_Sina_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordonnance_Medicament
    {
        public int id_ord_med { get; set; }
        public Nullable<int> Quantite { get; set; }
        public Nullable<int> NbrJr { get; set; }
        public string Nom_medic { get; set; }
        public Nullable<int> Ord_Num { get; set; }
        public Nullable<int> Id_Doc { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Ordonnance Ordonnance { get; set; }
    }
}
