//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hopita_Ibn_Sina_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Rendez_vous = new HashSet<Rendez_vous>();
        }
    
        public string Cin_pat { get; set; }
        public string Nom_pat { get; set; }
        public string Prenom_pat { get; set; }
        public string Genre_pat { get; set; }
        public System.DateTime DateNaissance_pat { get; set; }
        public string Adresse_pat { get; set; }
        public string Phone_pat { get; set; }
        public byte[] Image_pat { get; set; }
        public Nullable<int> Ord_Num { get; set; }
    
        public virtual Ordonnance Ordonnance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendez_vous> Rendez_vous { get; set; }
    }
}
