//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hopita_Ibn_Sina_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendez_vous
    {
        public int Id_rdv { get; set; }
        public System.DateTime Date_rdv { get; set; }
        public int Heure_rdv { get; set; }
        public int Id_Doc { get; set; }
        public string Cin_pat { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
